version: "3"
services:
    api:
       # container_name: "api"
      build:
        context: .
        dockerfile: ${DOCKER_FILE:-Dockerfile}
        #command: npm install mongodb
      ports:
        - 8000:8080
      volumes:
        - .:/var/app/data_volume
      env_file: .env
